// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHlkdWSvP0RLERv3dYszCB6rJG66CL49c',
    appId: '1:859123377401:android:f30635f06504ffcc926e28',
    messagingSenderId: '859123377401',
    projectId: 'beans-dev-c4111',
    storageBucket: 'beans-dev-c4111.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9vRTMVk4pilSRx8Nw1bGxhx5Y0GFBDrc',
    appId: '1:859123377401:ios:a6874919f5ccab6f926e28',
    messagingSenderId: '859123377401',
    projectId: 'beans-dev-c4111',
    storageBucket: 'beans-dev-c4111.appspot.com',
    androidClientId: '859123377401-u5fdp351l14oliv5g2nisdq4ek50i0cf.apps.googleusercontent.com',
    iosClientId: '859123377401-h1vm5u6pbgoe4bt14tg7poc1mq8ct528.apps.googleusercontent.com',
    iosBundleId: 'com.beansapp.app.dev',
  );
}
